name: bundle-desktop
on:
  push:
    branches:
      - staging
      - production
      - desktop
      - fix-windows-ci
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Adjust yarn timeout
        run: yarn config set network-timeout 1800000 -g

      - name: Install dependencies
        run: yarn --frozen-lockfile
        if: runner.os != 'Windows'

      - name: Install dependencies Windows
        run: |
          # https://github.com/microsoft/vscode/pull/144056/files
          # update node-gyp to latest for support in detecting VS 2022 toolchain
          npm install -g node-gyp@latest
          # Resolve to node-gyp.js
          # Remove this once node-version > 17.4.x or > 16.14.0,
          # which ships with npm > 8.4.0 that has support for VS 2022 toolchain.
          $env:npm_config_node_gyp=$(Join-Path $(Get-Command node-gyp.cmd).Path "..\node_modules\node-gyp\bin\node-gyp.js" -Resolve)
          yarn --frozen-lockfile
        if: runner.os == 'Windows'

      - name: Run linter
        run:  yarn lint

      # TODO re-enable
      # - name: Run test
      #   shell: bash
      #   run:  yarn test

      - name: Build with webpack for electron
        shell: bash
        run: ./scripts/build.sh -n Mainnet -e

      - name: Build on Mac
        run: yarn electron-builder --mac --publish never
        env:
          CSC_LINK: ${{ secrets.MAC_CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CSC_KEY_PASSWORD }}
        if: runner.os == 'macOS'

      - name: Build on Windows
        run: yarn electron-builder --win --publish never
        env:
          CSC_LINK: ${{ secrets.WINDOWS_CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CSC_KEY_PASSWORD }}
        if: runner.os == 'Windows'

      - name: Install deps for Linux
        run: sudo apt-get update && sudo apt-get install libudev-dev libusb-1.0-0-dev
        if: runner.os == 'Linux'
      
      - name: Build on Linux
        run: yarn electron-builder --linux --publish never
        if: runner.os == 'Linux'

      - uses: actions/upload-artifact@v2
        with:
          name: celowallet-artifacts
          path: |
            dist-electron/*-mac*.dmg
            dist-electron/*-mac*.zip
            dist-electron/*-linux*.AppImage
            dist-electron/*-win*.exe
