name: publish-windows
on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn --immutable

      - name: Build with webpack for electron
        shell: bash
        run: ./scripts/build.sh -n Mainnet -e
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          WALLET_CONNECT_KEY: ${{ secrets.WALLET_CONNECT_KEY }}

      - name: Build on Windows
        run: yarn electron-builder --win --publish always || yarn electron-builder --win --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CSC_LINK: ${{ secrets.WINDOWS_CSC_LINK2 }}
          # CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CSC_KEY_PASSWORD }}
          DISABLE_MULTIPART_DOWNLOADING: true