name: publish-windows
on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Adjust yarn timeout
        run: yarn config set network-timeout 600000 -g

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build with webpack for electron
        shell: bash
        run: ./scripts/build.sh -n Mainnet -e

      - name: Build on Windows
        run: yarn electron-builder --win --publish always || yarn electron-builder --win --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.WINDOWS_CSC_LINK2 }}
          CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CSC_KEY_PASSWORD }}
          DISABLE_MULTIPART_DOWNLOADING: true