name: publish-ubuntu
on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Adjust yarn timeout
        run: yarn config set network-timeout 600000 -g

      - name: Install dependencies
        run: yarn

      - name: Build with webpack for electron
        shell: bash
        run: ./scripts/build.sh -n Mainnet -e

      - name: Install deps for Linux
        run: sudo apt-get update && sudo apt-get install libudev-dev libusb-1.0-0-dev
      
      - name: Build on Linux
        run: |
          (echo "=== Build try 1: ===" && yarn electron-builder --linux --publish always) || \
          (echo "=== Build try 2: ===" && yarn electron-builder --linux --publish always) || \
          (echo "=== Build try 3: ===" && yarn electron-builder --linux --publish always) || \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}