name: publish-mac
on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Adjust yarn timeout
        run: yarn config set network-timeout 600000 -g

      - name: Install dependencies
        run: yarn

      - name: Build with webpack for electron
        shell: bash
        run: ./scripts/build.sh -n Mainnet -e

      - name: Build on Mac 
        run: |
          # Retry 3 times before the steps actually fails
          (echo "=== Build try 1: ===" && yarn electron-builder --mac --publish always) || \
          (echo "=== Build try 2: ===" && yarn electron-builder --mac --publish always) || \
          (echo "=== Build try 3: ===" && yarn electron-builder --mac --publish always) || \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.MAC_CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}