name: publish-ubuntu
on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Install dependencies
        run: yarn --immutable

      - name: Build with webpack for electron
        shell: bash
        run: ./scripts/build.sh -n Mainnet -e
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          WALLET_CONNECT_KEY: ${{ secrets.WALLET_CONNECT_KEY }}

      - name: Install deps for Linux
        run: sudo apt-get update && sudo apt-get install libudev-dev libusb-1.0-0-dev
      
      - name: Build on Linux
        run: yarn electron-builder --linux --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}